services:
  mysql:
    image: mysql:9.5.0
    container_name: mpay-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mpay
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
      - ./backend/src/main/resources/db:/docker-entrypoint-initdb.d
    command:
      - --lower_case_table_names=1
      - --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - mpay-net

  redis:
    image: redis:8.4.0
    container_name: mpay-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./infra/redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - mpay-net

networks:
  mpay-net:
    driver: bridge
