services:
  mysql:
    image: mysql:9.5.0
    container_name: mpay-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mpay
      MYSQL_USER: appuser
      MYSQL_PASSWORD: userpass
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mpay-net

  redis:
    image: redis:8.4.0
    container_name: mpay-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./infra/redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - mpay-net

networks:
  mpay-net:
    driver: bridge

